name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Hostinger
        run: ./deploy.sh
        env:
          HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
          HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
          # LOCAL_DIR: ${{ secrets.LOCAL_DIR }}
